### ISSUE TITLE
Module improvements

### ISSUE THREAD

**Issue by pi0** [fauzan121002/nuxt-web3#1]
Since adding module to modules.nuxtjs.org, here are few improvement suggestions:

- Avoid using require in plugin.js (use ESM import for future compatibility with nuxt3 and vite)
- Prefer using consola for logging for tooling consistency ([example](https://github.com/nuxt/http/blob/cd5a14ef031ab76f83bbf451bb95a18356d553bb/lib/module.js#L4))

Thanks for the nice module!

**Comment by fauzan121002** [comment]
> Since adding module to modules.nuxtjs.org, here are few improvement suggestions:
> 
> * Avoid using require in plugin.js (use ESM import for future compatibility with nuxt3 and vite)
> * Prefer using consola for logging for tooling consistency ([example](https://github.com/nuxt/http/blob/cd5a14ef031ab76f83bbf451bb95a18356d553bb/lib/module.js#L4))
> 
> Thanks for the nice module!

Thanks, will working on it!

**Comment by fauzan121002** [comment]
@pi0 already fulfilled the suggestions, i will close it.

**Comment by pi0** [comment]
That was fast! Thanks :)
